apiVersion: v1
name: puppetserver
version: 5.0.1
appVersion: 6.12.1
description: Puppet automates the delivery and operation of software.
keywords: ["puppet", "puppetserver", "automation", "iac", "infrastructure", "cm", "ci", "cd"]
home: https://puppet.com/
icon: https://secure.gravatar.com/avatar/fdd009b7c1ec96e088b389f773e87aec.jpg?s=80&r=g&d=mm
sources:
  - https://github.com/puppetlabs/pupperware/
  - https://github.com/postgres/postgres
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
maintainers:
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
  - name: underscorgan
    email: morgan@puppet.com
  - name: slconley
    email: slconley@gmail.com
  - name: Pupperware Team
    email: pupperware@puppet.com
engine: gotpl
kubeVersion: ">=1.10.0-0"
