{{- if .Values.hiera.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "puppetserver.fullname" . }}-hiera-config
  labels:
    {{- include "puppetserver.hiera.labels" . | nindent 4 }}
data:
  hiera.yaml: |-
    {{ .Values.hiera.config | nindent 4 }}
{{- end }}
