{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-custom-extensions
  labels:
    {{- include "puppetserver.postgresql.labels" . | nindent 4 }}
data:
  extensions.sql: |
    CREATE EXTENSION IF NOT EXISTS pg_trgm;
    CREATE EXTENSION IF NOT EXISTS pgcrypto;
{{- end }}
