{{- if and (.Values.puppetdb.enabled) (.Values.puppetdb.metrics.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "puppetdb.fullname" . }}-metrics-config
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.puppetdb.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  metrics.conf: |
    metrics: {
      # a server id that will be used as part of the namespace for metrics produced
      # by this server
      server-id: localhost
      registries: {
          puppetserver: {
              # specify metrics to allow in addition to those in the default list
              #metrics-allowed: ["compiler.compile.production"]

              reporters: {
                  # enable or disable JMX metrics reporter
                  jmx: {
                      enabled: true
                  }
                  # enable or disable Graphite metrics reporter
                  #graphite: {
                  #    enabled: true
                  #}
              }
          }
      }

      # this section is used to configure settings for reporters that will send
      # the metrics to various destinations for external viewing
      reporters: {
          #graphite: {
          #    # graphite host
          #    host: "127.0.0.1"
          #    # graphite metrics port
          #    port: 2003
          #    # how often to send metrics to graphite
          #    update-interval-seconds: 5
          #}
      }
      metrics-webservice: {
          jolokia: {
              # Enable or disable the Jolokia-based metrics/v2 endpoint.
              # Default is true.
              # enabled: false

              # Configure any of the settings listed at:
              #   https://jolokia.org/reference/html/agents.html#war-agent-installation
              servlet-init-params: {
                  # Specify a custom security policy:
                  #  https://jolokia.org/reference/html/security.html
                  debug: "true"
                  policyLocation: "file:///etc/puppetlabs/puppetdb/jolokia-access.xml"
              }
          }
      }
    }

  jolokia-access.xml: |
    <?xml version="1.0" encoding="utf-8"?>
    <restrict>
      <remote>
        <host>0.0.0.0/0</host>
      </remote>

      <commands>
        <command>read</command>
        <command>list</command>
        <command>version</command>
        <command>search</command>
      </commands>

      <mbean>
        <name>puppetlabs.puppetdb.population:name=num-nodes</name>
        <attribute mode="read">Value</attribute>
        <operation>objectName</operation>
      </mbean>
    </restrict>
{{- end -}}
