{{- if and (.Values.puppetserver.serviceAccount.enabled) (.Values.puppetserver.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.puppetserver.serviceAccount.accountName | default "puppet" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
{{- end }}