{{- if and .Values.puppetserver.compilers.enabled .Values.puppetserver.compilers.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $serviceName := include "puppetserver.puppetserver-compilers.serviceName" . }}
{{- $servicePort := .Values.puppetserver.compilers.service.ports.puppetserver.port -}}
{{- $pathType := .Values.puppetserver.compilers.ingress.pathType | default "ImplementationSpecific" -}}
{{- $apiIsStable := eq (include "puppetserver.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "puppetserver.ingress.supportsPathType" .) "true" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.puppetserver.compilers.ingress.annotations }}
  annotations:
    {{ toYaml .Values.puppetserver.compilers.ingress.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.puppetserver.compilers.ingress.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  name: {{ template "puppetserver.fullname" . }}-compilers
spec:
  rules:
    {{- range .Values.puppetserver.compilers.ingress.hosts }}
    {{- $url := splitList "/" . }}
    - host: {{ first $url }}
      http:
        paths:
          - path: /{{ rest $url | join "/" }}
            {{- if and $pathType $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.puppetserver.compilers.ingress.tls }}
  tls:
    {{ toYaml .Values.puppetserver.compilers.ingress.tls | nindent 4 }}
  {{- end -}}
{{- end -}}
