{{- if and (.Values.puppetserver.serviceAccount.enabled) (.Values.puppetserver.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "puppetserver.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if or .Values.puppetserver.preGeneratedCertsJob.enabled .Values.singleCA.enabled .Values.global.runAsNonRoot }}
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    {{- end }}
    {{- with .Values.puppetserver.serviceAccount.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
