{{- if and (.Values.puppetdb.enabled) (.Values.puppetdb.rbac.create) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "puppetdb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.puppetdb.extraLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    {{- with .Values.puppetdb.rbac.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "puppetdb.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "puppetdb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
