{{- if .Values.puppetserver.compilers.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "puppetserver.name" . }}-puppetserver-compiler
  labels:
    {{- include "puppetserver.puppetserver-compilers.labels" . | nindent 4 }}
  {{- if .Values.puppetserver.compilers.annotations }}
  annotations:
    {{- toYaml .Values.puppetserver.compilers.annotations | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ template "puppetserver.puppetserver-compilers.serviceName" . }}-headless
  selector:
    matchLabels:
      {{- include "puppetserver.puppetserver-compilers.matchLabels" . | nindent 6 }}
  {{- if not (.Values.puppetserver.compilers.autoScaling.enabled) }}
  replicas: {{ .Values.puppetserver.compilers.manualScaling.compilers }}
  {{- end }}
  podManagementPolicy: {{ .Values.puppetserver.compilers.podManagementPolicy }}
  {{- if .Values.puppetserver.compilers.updateStrategy }}
  updateStrategy: {{- toYaml .Values.puppetserver.compilers.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "puppetserver.puppetserver-compilers.labels" . | nindent 8 }}
      annotations:
        checksum/hiera-configmap: {{ include (print $.Template.BasePath "/hiera-configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.puppetserver.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.puppetserver.serviceAccount.accountName }}
      {{- end }}
      initContainers:
        - name: perms-and-dirs
          image: "{{.Values.puppetserver.image}}:{{.Values.puppetserver.tag}}"
          imagePullPolicy: "{{.Values.puppetserver.pullPolicy}}"
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 300m
          command: [ "sh", "-c" ]
          args:
            - mkdir -p /etc/puppetlabs/puppet/eyaml/keys;
              mkdir -p /etc/puppetlabs/code/environments;
              mkdir -p /etc/puppetlabs/puppet/manifests;
              chown -R puppet:puppet /etc/puppetlabs;
              {{- if .Values.hiera.config }}
              cp /etc/puppetlabs/puppet/configmap/hiera.yaml /etc/puppetlabs/puppet/hiera.yaml;
              chown puppet:puppet /etc/puppetlabs/puppet/hiera.yaml;
              {{- end }}
              cp /etc/puppetlabs/puppet/configmap/site.pp /etc/puppetlabs/puppet/manifests/site.pp;
              chown puppet:puppet /etc/puppetlabs/puppet/manifests/site.pp;
              {{- if or (.Values.hiera.eyaml.private_key) (.Values.hiera.eyaml.existingMap) }}
              cp /etc/puppetlabs/puppet/configmap/eyaml/*private_key.pkcs7.pem /etc/puppetlabs/puppet/eyaml/keys/;
              chown puppet:puppet /etc/puppetlabs/puppet/eyaml/keys/*private_key.pkcs7.pem;
              {{- end }}
              {{- if or (.Values.hiera.eyaml.public_key) (.Values.hiera.eyaml.existingMap) }}
              cp /etc/puppetlabs/puppet/configmap/eyaml/*public_key.pkcs7.pem /etc/puppetlabs/puppet/eyaml/keys/;
              chown puppet:puppet /etc/puppetlabs/puppet/eyaml/keys/*public_key.pkcs7.pem;
              {{- end }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            privileged: true
          volumeMounts:
            - name: puppet-code-volume
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-volume
              mountPath: /etc/puppetlabs/puppet/
            {{- if .Values.hiera.config }}
            - name: hiera-volume
              mountPath: /etc/puppetlabs/puppet/configmap/hiera.yaml
              subPath: hiera.yaml
            {{- end }}
            - name: manifests-volume
              mountPath: /etc/puppetlabs/puppet/configmap/site.pp
              subPath: site.pp
            {{- if .Values.hiera.eyaml.existingMap }}
            - name: eyaml-volume
              mountPath: /etc/puppetlabs/puppet/configmap/eyaml
            {{- end }}
            {{- if and (.Values.hiera.eyaml.public_key) (not .Values.hiera.eyaml.existingMap)}}
            - name: eyamlpub-volume
              mountPath: /etc/puppetlabs/puppet/configmap/eyaml/public_key.pkcs7.pem
              subPath: public_key.pkcs7.pem
            {{- end }}
            {{- if and (.Values.hiera.eyaml.private_key) (not .Values.hiera.eyaml.existingMap)}}
            - name: eyamlpriv-volume
              mountPath: /etc/puppetlabs/puppet/configmap/eyaml/private_key.pkcs7.pem
              subPath: private_key.pkcs7.pem
            {{- end }}
      containers:
        - name: {{ template "puppetserver.fullname" . }}
          image: "{{.Values.puppetserver.image}}:{{.Values.puppetserver.tag}}"
          imagePullPolicy: "{{.Values.puppetserver.pullPolicy}}"
          resources:
            {{- toYaml .Values.puppetserver.compilers.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.puppetserver.compilers.extraEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            # necessary to set certname and server in puppet.conf, required by
            # puppetserver ca cli application
            - name: PUPPETSERVER_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PUPPET_MASTERPORT
              value: "{{ template "puppetserver.puppetserver-compilers.port" . }}"
            - name: DNS_ALT_NAMES
              value: "{{ template "puppetserver.puppetserver-compilers.serviceName" . }},{{.Values.puppetserver.compilers.fqdns.alternateServerNames}}"
            - name: PUPPETDB_SERVER_URLS
              value: "https://puppetdb:8081"
            - name: CA_ENABLED
              value: "false"
            - name: CA_HOSTNAME
              value: "{{ template "puppetserver.puppetserver-masters.serviceName" . }}"
            - name: CA_MASTERPORT
              value: "{{ template "puppetserver.puppetserver-masters.port" . }}"
          readinessProbe:
            httpGet:
              path: /status/v1/simple
              port: {{ template "puppetserver.puppetserver-compilers.port" . }}
              scheme: HTTPS
            initialDelaySeconds: {{ .Values.puppetserver.compilers.readinessProbeInitialDelay }}
            periodSeconds: {{ .Values.puppetserver.compilers.readinessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.puppetserver.compilers.readinessProbeTimeout }}
            failureThreshold: {{ .Values.puppetserver.compilers.readinessProbeFailureThreshold }}
            successThreshold: {{ .Values.puppetserver.compilers.readinessProbeSuccessThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ template "puppetserver.puppetserver-compilers.port" . }}
            initialDelaySeconds: {{ .Values.puppetserver.compilers.livenessProbeInitialDelay }}
            periodSeconds: {{ .Values.puppetserver.compilers.livenessProbePeriodSeconds }}
            timeoutSeconds: {{ .Values.puppetserver.compilers.livenessProbeTimeout }}
            failureThreshold: {{ .Values.puppetserver.compilers.livenessProbeFailureThreshold }}
            successThreshold: {{ .Values.puppetserver.compilers.livenessProbeSuccessThreshold }}
          ports:
            - containerPort: {{ template "puppetserver.puppetserver-compilers.port" . }}
          volumeMounts:
            - name: puppet-code-volume
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-volume
              mountPath: /etc/puppetlabs/puppet/
      securityContext:
        fsGroup: 999   # "puppet" GID
      volumes:
        - name: puppet-code-volume
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.code.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.code.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-code-claim
        {{- end }}
        {{- if .Values.hiera.config }}
        - name: hiera-volume
          configMap:
            name: hiera-config
        {{- end }}
        - name: manifests-volume
          configMap:
            name: manifests-config
        {{- if .Values.hiera.eyaml.existingSecret }}
        - name: eyaml-volume
          secret:
            secretName: {{ .Values.hiera.eyaml.existingSecret }}
        {{- else if .Values.hiera.eyaml.existingMap }}
        - name: eyaml-volume
          configMap:
            name: {{ .Values.hiera.eyaml.existingMap }}
        {{- end }}
        {{- if and (.Values.hiera.eyaml.public_key) (not .Values.hiera.eyaml.existingMap) (not .Values.hiera.eyaml.existingSecret)}}
        - name: eyamlpub-volume
          secret:
            secretName: {{ template "puppetserver.hiera.publicSecret" . }}
        {{- end }}
        {{- if and (.Values.hiera.eyaml.private_key) (not .Values.hiera.eyaml.existingMap) (not .Values.hiera.eyaml.existingSecret)}}
        - name: eyamlpriv-volume
          secret:
            secretName: {{ template "puppetserver.hiera.privateSecret" . }}
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 10 }}
      {{- end }}
      {{ template "puppetserver.compilers.affinity" . }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations| nindent 10 }}
      {{- end }}
      {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.priorityClassName) }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: puppet-puppet-volume
      {{- if .Values.storage.annotations }}
      annotations:
        {{- toYaml .Values.storage.annotations | nindent 10 }}
      {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.storage.accessModes | nindent 10 }}
        resources:
          requests:
            storage: "{{ .Values.storage.size }}"
        {{- if .Values.storage.storageClass }}
        {{- if (eq "-" .Values.storage.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.storage.storageClass }}"
        {{- end }}
        {{- end }}
{{- end }}
