{{- if and .Values.puppetserver.masters.backup.enabled (not .Values.singleCA.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetserver.fullname" . }}-restic-backup-creds
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- with .Values.puppetserver.masters.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- with .Values.puppetserver.masters.backup.restic }}
  {{- if .password }}
  restic_password: {{ .password | b64enc | quote }}
  {{- end }}
  {{- if .access_key_id }}
  access_key_id: {{ .access_key_id | b64enc | quote }}
  {{- end }}
  {{- if .secret_access_key }}
  secret_access_key: {{ .secret_access_key | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
