{{- if .Values.puppetserver.compilers.enabled }}
{{- if .Values.puppetserver.compilers.autoScaling.enabled }}
apiVersion: {{ include "puppetserver.autoscaling.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "puppetserver.fullname" . }}-compilers-autoscaler
  labels:
    {{- include "puppetserver.puppetserver-compilers.labels" . | nindent 4 }}
    {{- with .Values.puppetserver.compilers.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.puppetserver.compilers.kind }}
    name: {{ template "puppetserver.fullname" . }}-puppetserver-compiler
  minReplicas: {{ .Values.puppetserver.compilers.autoScaling.minCompilers }}
  maxReplicas: {{ .Values.puppetserver.compilers.autoScaling.maxCompilers }}
  metrics:
  {{- with .Values.puppetserver.compilers.autoScaling.cpuUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.puppetserver.compilers.autoScaling.memoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
