{{- if not .Values.puppetserver.customPersistentVolumeClaim.code.enable }}
{{- if or ( eq .Values.puppetserver.compilers.kind "Deployment" ) ( not .Values.puppetserver.compilers.enabled ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "puppetserver.fullname" . }}-code-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- with .Values.global.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.storage.annotations }}
  annotations:
    {{ toYaml .Values.storage.annotations | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClass }}
  {{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
