{{- if and (.Values.puppetdb.serviceAccount.enabled) (.Values.puppetdb.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "puppetdb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.puppetdb.serviceAccount.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
