{{- if .Values.puppetserver.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "puppetserver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- with .Values.puppetserver.masters.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if or (.Values.puppetserver.preGeneratedCertsJob.enabled) (.Values.singleCA.enabled) }}
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-10"
    {{- end }}
    {{- with .Values.puppetserver.rbac.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "puppetserver.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "puppetserver.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
