{{- if and (not .Values.puppetserver.customPersistentVolumeClaim.puppetserver.enable) .Values.global.runAsNonRoot }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "puppetserver.fullname" . }}-puppetserver-claim
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- with .Values.global.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.global.runAsNonRoot }}
    helm.sh/hook: pre-install
    {{- end }}
    {{- with .Values.storage.annotations -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
  {{- if .Values.storage.storageClass }}
  {{- if (eq "-" .Values.storage.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.storage.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
