{{- if and .Values.puppetdb.enabled .Values.metrics.prometheus.enabled }}
  {{- if (not (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")) }}
    {{- if (not (.Values.metrics.prometheus.disableAPICheck)) }}
      {{- fail "ERROR: You have to deploy monitoring.coreos.com/v1 first" }}
    {{- end }}
  {{- end }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "puppetdb.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.prometheus.namespace | quote }}
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheus.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    release: kube-prometheus-stack
spec:
  jobLabel: {{ .Values.metrics.prometheus.jobLabel | default "{{.Release.Name }}-puppetdb" }}
  endpoints:
    - port: metrics
      path: /metrics
      {{- with .Values.metrics.prometheus.honorLabels }}
      honorLabels: {{ . }}
      {{- end }}
      {{- with .Values.metrics.prometheus.honorTimestamps }}
      honorTimestamps: {{ . }}
      {{- end }}
      {{- with .Values.metrics.prometheus.enableHttp2 }}
      enableHttp2: {{ . }}
      {{- end }}
      {{- with .Values.metrics.prometheus.followRedirects }}
      followRedirects: {{ . }}
      {{- end }}
      {{- with .Values.metrics.prometheus.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.prometheus.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- if .Values.metrics.prometheus.metricRelabelings }}
      metricRelabelings:
      {{ tpl (toYaml .Values.metrics.prometheus.metricRelabelings | indent 6) . }}
      {{- end }}
      {{- if .Values.metrics.prometheus.relabelings }}
      relabelings:
      {{ toYaml .Values.metrics.prometheus.relabelings | indent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "puppetserver.puppetdb.matchLabels" . | nindent 6 }}
{{- end }}