---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "puppetserver.fullname" . }}-manifests-config
  labels:
    {{- include "puppetserver.puppetserver.labels" . | nindent 4 }}
    {{- with .Values.puppetserver.masters.extraLabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  site.pp: |
    hiera_include('classes')
