{{- if .Values.puppetdb.enabled }}
{{- if not .Values.global.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetdb.secret" . }}
  labels:
    {{- include "puppetserver.puppetdb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.global.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.global.postgresql.auth.password | b64enc | quote }}
{{- end }}
---
{{- if .Values.puppetboard.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: puppetdb-puppetboard
type: Opaque
data:
  {{- $secret := lookup "v1" "Secret" .Release.Namespace "puppetdb-puppetboard" }}
  {{- if $secret }}
  SECRET_KEY: {{ $secret.data.SECRET_KEY }}
  {{- else }}
  SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
