{{- if and (include "hiera.enable" .) (and (not .Values.r10k.hiera.viaSsh.credentials.existingSecret) (not .Values.r10k.hiera.viaHttps.credentials.existingSecret)) }}
{{- if or (and (.Values.r10k.hiera.viaSsh.credentials.ssh.value) (.Values.r10k.hiera.viaSsh.credentials.known_hosts.value)) (.Values.r10k.hiera.viaHttps.credentials) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "puppetserver.fullname" . }}-r10k-hiera-creds
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.r10k.hiera.viaSsh.credentials }}
  {{- if and (.ssh.value) (.known_hosts.value) }}
  id_rsa: {{ .ssh.value | b64enc | quote }}
  known_hosts: {{ .known_hosts.value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.r10k.hiera.viaHttps.credentials }}
  {{- if .netrc.value }}
  netrc: {{ .netrc.value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
