{{- if or (.Values.puppetserver.puppeturl) (include "hiera.enable" .) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "puppetserver.name" . }}-r10k
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "puppetserver.r10k.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "puppetserver.r10k.labels" . | nindent 8 }}
      annotations:
        checksum/r10k-hiera-config: {{ include (print $.Template.BasePath "/r10k-hiera.configmap.yaml") . | sha256sum }}
        checksum/r10k-hiera-secret: {{ include (print $.Template.BasePath "/r10k-hiera-secret.yaml") . | sha256sum }}
        checksum/r10k-code-config: {{ include (print $.Template.BasePath "/r10k-code.configmap.yaml") . | sha256sum }}
        checksum/r10k-code-secret: {{ include (print $.Template.BasePath "/r10k-code-secret.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.r10k.serviceAccount.enabled }}
      serviceAccountName: {{  default "r10k" .Values.r10k.serviceAccount.accountName }}
      {{- end }}
      initContainers:
        - name: perms-and-dirs
          image: "{{.Values.puppetserver.image}}:{{.Values.puppetserver.tag}}"
          imagePullPolicy: "{{.Values.puppetserver.pullPolicy}}"
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 300m
          command: [ "sh", "-c" ]
          args:
            - mkdir -p /etc/puppetlabs/code/r10k_cache;
              chown -R puppet:puppet /etc/puppetlabs;
              {{- if .Values.puppetserver.puppeturl }}
              cp /etc/puppetlabs/puppet/configmap/r10k_code_entrypoint.sh /etc/puppetlabs/puppet/r10k_code_entrypoint.sh;
              cp /etc/puppetlabs/puppet/configmap/r10k_code_cronjob.sh /etc/puppetlabs/puppet/r10k_code_cronjob.sh;
              cp /etc/puppetlabs/puppet/configmap/r10k_code.yaml /etc/puppetlabs/puppet/r10k_code.yaml;
              chown puppet:puppet /etc/puppetlabs/puppet/r10k_code_entrypoint.sh /etc/puppetlabs/puppet/r10k_code_cronjob.sh /etc/puppetlabs/puppet/r10k_code.yaml;
              chmod +x /etc/puppetlabs/puppet/r10k_code_entrypoint.sh /etc/puppetlabs/puppet/r10k_code_cronjob.sh;
              {{- end }}
              {{- if (include "hiera.enable" .) }}
              cp /etc/puppetlabs/puppet/configmap/r10k_hiera_entrypoint.sh /etc/puppetlabs/puppet/r10k_hiera_entrypoint.sh;
              cp /etc/puppetlabs/puppet/configmap/r10k_hiera_cronjob.sh /etc/puppetlabs/puppet/r10k_hiera_cronjob.sh;
              cp /etc/puppetlabs/puppet/configmap/r10k_hiera.yaml /etc/puppetlabs/puppet/r10k_hiera.yaml;
              chown puppet:puppet /etc/puppetlabs/puppet/r10k_hiera_entrypoint.sh /etc/puppetlabs/puppet/r10k_hiera_cronjob.sh /etc/puppetlabs/puppet/r10k_hiera.yaml;
              chmod +x /etc/puppetlabs/puppet/r10k_hiera_entrypoint.sh /etc/puppetlabs/puppet/r10k_hiera_cronjob.sh;
              {{- end }}
          securityContext:
            runAsUser: 0
            runAsNonRoot: false
            privileged: true
          volumeMounts:
            - name: puppet-code-storage
              mountPath: /etc/puppetlabs/code/
            - name: puppet-puppet-storage
              mountPath: /etc/puppetlabs/puppet/
            {{- if .Values.puppetserver.puppeturl }}
            - name: r10k-code-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_code_entrypoint.sh
              subPath: r10k_code_entrypoint.sh
            - name: r10k-code-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_code_cronjob.sh
              subPath: r10k_code_cronjob.sh
            - name: r10k-code-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_code.yaml
              subPath: r10k_code.yaml
            {{- end }}
            {{- if (include "hiera.enable" .) }}
            - name: r10k-hiera-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_hiera_entrypoint.sh
              subPath: r10k_hiera_entrypoint.sh
            - name: r10k-hiera-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_hiera_cronjob.sh
              subPath: r10k_hiera_cronjob.sh
            - name: r10k-hiera-volume
              mountPath: /etc/puppetlabs/puppet/configmap/r10k_hiera.yaml
              subPath: r10k_hiera.yaml
            {{- end }}
      containers:
        {{- if .Values.puppetserver.puppeturl }}
        # r10k Code Sidecar
        - name: r10k-code
          image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
          imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
          resources:
            {{- toYaml .Values.r10k.code.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.r10k.code.extraEnv }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          command: [ "sh", "-c", "/etc/puppetlabs/puppet/r10k_code_entrypoint.sh" ]
          securityContext:
            runAsUser: 999   # "puppet" UID
            runAsGroup: 999 # "puppet" GID
          volumeMounts:
          {{- with .Values.r10k.code.viaSsh.credentials }}
          {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
          - name: r10k-code-ssh
            mountPath: /home/puppet/.ssh
          {{- end }}
          {{- end }}
          {{- with .Values.r10k.code.viaHttps.credentials }}
          {{- if or .existingSecret .netrc.value }}
          - name: r10k-code-netrc
            mountPath: /home/puppet/.netrc
            subPath: .netrc
          {{- end }}
          {{- end }}
          - name: puppet-code-storage
            mountPath: /etc/puppetlabs/code/
          - name: puppet-puppet-storage
            mountPath: /etc/puppetlabs/puppet/
          readinessProbe:
            exec:
              command: ["/bin/sh", "-ec", "test -f ~/.r10k_code_cronjob.success"]
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
        {{- end }}
        {{- if (include "hiera.enable" .) }}
        # r10k Hiera Sidecar
        - name: r10k-hiera
          image: "{{.Values.r10k.image}}:{{.Values.r10k.tag}}"
          imagePullPolicy: "{{.Values.r10k.pullPolicy}}"
          resources:
            {{- toYaml .Values.r10k.hiera.resources | nindent 12 }}
          env:
          {{- range $key, $value := .Values.r10k.hiera.extraEnv }}
          - name: {{ $key }}
            value: "{{ $value }}"
          {{- end }}
          command: [ "sh", "-c", "/etc/puppetlabs/puppet/r10k_hiera_entrypoint.sh" ]
          securityContext:
            runAsUser: 999   # "puppet" UID
            runAsGroup: 999 # "puppet" GID
          volumeMounts:
          {{- with .Values.r10k.hiera.viaSsh.credentials }}
          {{- if or (.existingSecret) (and (.ssh.value) (.known_hosts.value)) }}
          - name: r10k-hiera-ssh
            mountPath: /home/puppet/.ssh
          {{- end }}
          {{- end }}
          {{- with .Values.r10k.hiera.viaHttps.credentials }}
          {{- if or .existingSecret .netrc.value }}
          - name: r10k-hiera-netrc
            mountPath: /home/puppet/.netrc
            subPath: .netrc
          {{- end }}
          {{- end }}
          - name: puppet-code-storage
            mountPath: /etc/puppetlabs/code/
          - name: puppet-puppet-storage
            mountPath: /etc/puppetlabs/puppet/
          readinessProbe:
            exec:
              command: ["/bin/sh", "-ec", "test -f ~/.r10k_hiera_cronjob.success"]
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
        {{- end }}
      securityContext:
        fsGroup: 999   # "puppet" GID
      volumes:
        - name: puppet-code-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.code.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.code.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-code-claim
        {{- end }}
        - name: puppet-puppet-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.puppet.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.puppet.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-puppet-claim
        {{- end }}
        - name: puppet-serverdata-storage
        {{- if .Values.puppetserver.masters.customPersistentVolumeClaim.serverdata.enable }}
          {{- toYaml .Values.puppetserver.masters.customPersistentVolumeClaim.serverdata.config | nindent 10 }}
        {{- else }}
          persistentVolumeClaim:
            claimName: puppet-serverdata-claim
        {{- end }}
        {{- if or (.Values.r10k.code.viaSsh.credentials.existingSecret) (and (.Values.r10k.code.viaSsh.credentials.ssh.value) (.Values.r10k.code.viaSsh.credentials.known_hosts.value)) }}
        - name: r10k-code-ssh
          secret:
            secretName: {{ template "r10k.code.viaSsh.secret" . }}
            defaultMode: 288 # = mode 0440
            items:
              - key: id_rsa
                path: id_rsa
              - key: known_hosts
                path: known_hosts
        {{- end }}
        {{- if or .Values.r10k.code.viaHttps.credentials.existingSecret .Values.r10k.code.viaHttps.credentials.netrc.value }}
        - name: r10k-code-netrc
          secret:
            secretName: {{ template "r10k.code.viaHttps.secret" . }}
            defaultMode: 288 # = mode 0440
            items:
              - key: netrc
                path: .netrc
        {{- end }}
        {{- if .Values.puppetserver.puppeturl }}
        - name: r10k-code-volume
          configMap:
            name: r10k-code-config
        {{- end }}
        {{- if (include "hiera.enable" .) }}
        - name: r10k-hiera-volume
          configMap:
            name: r10k-hiera-config
        {{- end }}
        {{- if or (.Values.r10k.hiera.viaSsh.credentials.existingSecret) (and (.Values.r10k.hiera.viaSsh.credentials.ssh.value) (.Values.r10k.hiera.viaSsh.credentials.known_hosts.value)) }}
        - name: r10k-hiera-ssh
          secret:
            secretName: {{ template "r10k.hiera.viaSsh.secret" . }}
            defaultMode: 288 # = mode 0440
            items:
              - key: id_rsa
                path: id_rsa
              - key: known_hosts
                path: known_hosts
        {{- end }}
        {{- if or .Values.r10k.hiera.viaHttps.credentials.existingSecret .Values.r10k.hiera.viaHttps.credentials.netrc.value }}
        - name: r10k-hiera-netrc
          secret:
            secretName: {{ template "r10k.hiera.viaHttps.secret" . }}
            defaultMode: 288 # = mode 0440
            items:
              - key: netrc
                path: .netrc
        {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.nodeSelector | nindent 10 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
      {{ toYaml .Values.affinity | nindent 10 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ toYaml .Values.tolerations| nindent 10 }}
      {{- end }}
      {{- if and (.Capabilities.APIVersions.Has "scheduling.k8s.io/v1beta1") (.Values.priorityClassName) }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
{{- end }}
