{{- if .Values.hiera.hieradataurl }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: r10k-hiera-config
  labels:
    {{- include "puppetserver.r10k.labels" . | nindent 4 }}
data:
  r10k_hiera.yaml: |
    # The location to use for storing cached Git repos
    :cachedir: '/etc/puppetlabs/code/r10k_cache'
    # A list of git repositories to create
    :sources:
      # This will clone the git repository and instantiate an environment per
      # branch in '/etc/puppetlabs/code/hiera-data'
      :hiera_repo:
        remote: '{{.Values.hiera.hieradataurl}}'
        basedir: '/etc/puppetlabs/code/hiera-data'

  r10k_hiera_cronjob.sh: |
    #!/usr/bin/env sh
    /docker-entrypoint.sh deploy environment --config /etc/puppetlabs/puppet/r10k_hiera.yaml \
    --puppetfile {{ template "r10k.hiera.args" . }} > ~/.r10k_hiera_cronjob.out 2>&1
    retVal=$?
    if [ "$retVal" -eq "0" ]; then
      touch ~/.r10k_hiera_cronjob.success > /dev/null 2>&1
    else
      rm ~/.r10k_hiera_cronjob.success > /dev/null 2>&1
    fi
    exit $retVal

  r10k_hiera_entrypoint.sh: |
    #!/usr/bin/env sh
    set -e
    cat > ~/.r10k_hiera_crontab <<'EOF'
    {{ .Values.r10k.hiera.cronJob.schedule }} /bin/sh -c /etc/puppetlabs/puppet/r10k_hiera_cronjob.sh
    EOF
    tail -Fq ~/.r10k_hiera_cronjob.out &
    touch ~/.r10k_hiera_cronjob.success > /dev/null 2>&1
    exec supercronic ~/.r10k_hiera_crontab
{{- end }}
